AllCops:
  TargetRubyVersion: 3.0.2

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe']
